---

- name: Insert Syslog Server Name in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "{{ syslogng_server_prefix }}.{{ syslogng_server_suffix }}"
    line: "10.255.255.10        {{ syslogng_server_prefix }}.{{ syslogng_server_suffix }}"
    insertafter: EOF
