---

- name: Insert Syslog Server Name in client /etc/hosts
  hosts: client
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "{{ syslogng_server_prefix }}.{{ syslogng_server_suffix }}"
    line: "{{syslogng_server_ip }} {{ syslogng_server_prefix }}.{{ syslogng_server_suffix }}"
    insertafter: EOF

- name: Insert Syslog Client Name in server /etc/hosts
  hosts: server
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "{{ syslogng_dn_prefix }}.{{ syslogng_dn_suffix }}"
    line: "{{syslogng_client_ip }} {{ syslogng_dn_prefix }}.{{ syslogng_dn_suffix }}"
    insertafter: EOF
