---

- name: Install Syslog-ng
  yum:
    name: syslog-ng
    state: present

- name: Populate service facts
  service_facts:
  tags: config

- name: Gather NGINX log files if needed
  find:
    paths: /var/log/nginx/
    patterns: "*.log"
    recurse: yes
  register: nginx_logs
  when: "services is defined and 'nginx.service' in services"
  tags: config

- name: Gather HTTPD log files if needed
  find:
    paths: /var/log/httpd/
    patterns: "*_log"
    recurse: yes
  register: httpd_logs
  when: "services is defined and 'httpd.service' in services"
  tags: config

- name: Gather MariaDB log files if needed
  find:
    paths: /var/log/mariadb/
    patterns: "*.log"
    recurse: yes
  register: mariadb_logs
  when: "services is defined and 'mariadb.service' in services"
  tags: config

- name: Set if we need to tail
  set_fact:
    syslogng_tailer: ""
  when: (mariadb_logs is defined or httpd_logs is defined or nginx_logs is defined) and (syslogng_tailer is not defined)

- name: Configure Syslog-ng
  template:
    backup: yes
    src: syslog-ng.conf.j2
    dest: /etc/syslog-ng/syslog-ng.conf
    mode: 0644
    owner: root
    group: wheel
  notify: Enable syslog-ng
  tags: config
