---

- name: Install Syslog-ng
  yum:
    name: syslog-ng
    state: present

- name: Populate service facts
  service_facts:
  tags: config

- name: Gather NGINX log files if needed
  find: 
    paths: /var/log/nginx/
    patterns: "*.log"
    recurse: yes
  register: nginx_logs
  when: "'nginx.service' in services"
  tags: config

- name: Gather HTTPD log files if needed
  find:
    paths: /var/log/httpd/
    patterns: "*_log"
    recurse: yes
  register: httpd_logs
  when: "'httpd.service' in services"
  tags: config

- name: Configure Syslog-ng
  template:
    backup: yes
    src: syslog-ng.conf.j2
    dest: /etc/syslog-ng/syslog-ng.conf
    mode: 0644
    owner: root
    group: wheel
  notify: Enable syslog-ng
  tags: config
